stages:
  - build
  - test

build:
  image: docker:latest
  tags:
    - l0cal, d0cker, tim-pc
  script:
    - docker build -t hr .
    - docker run -p 5000:5000 hr

test:
  image: docker:latest
  tags:
    - l0cal, d0cker, tim-pc
  needs:
    - build
  script:
    - set DB_NAME=%DB_NAME%
    - set DB_USER=%DB_USER%
    - set DB_PASS=%DB_PASS%
    - set DB_SERVER=%DB_SERVER%
    - set JWT=%JWT%
    - npx mocha test/routes/*.js
