stages:
  - test
  - build
  - publish

variables:
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASS: $DB_PASS
  DB_SERVER: $DB_SERVER
  JWT: $JWT

test_server:
  stage: test
  image: node:latest
  tags:
    - she11
  before_script:
    - pwd
    - npm install
  script:
    - pwd
    - npx mocha test/routes/*.js

build_docker_image:
  stage: build
  tags:
    - she11
  before_script:
    - $IMAGE_VERSION = Get-Content version.txt
  script:
    - pwd
    - docker build -t ${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}-build${CI_PIPELINE_IID} .
    - docker tag ${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}-build${CI_PIPELINE_IID} latest
    - docker images

push_to_registry:
  stage: publish
  tags:
    - she11
  needs:
    - build_docker_image
  before_script:
    - $IMAGE_VERSION = Get-Content version.txt
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - pwd
    - docker push ${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}-build${CI_PIPELINE_IID}
    - docker images
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker images
