stages:
  - test

run unit test:
  stage: test
  image: node:latest
  tags:
    - she11
  before_script:
    - npm install
  script:
    - pwd
    - set DB_NAME=%DB_NAME%
    - set DB_USER=%DB_USER%
    - set DB_PASS=%DB_PASS%
    - set DB_SERVER=%DB_SERVER%
    - set JWT=%JWT%
    - cd server
    - npx mocha test/routes/*.js
