stages:
  - build
  - test

build:
  stage: build
  tags:
  - D0cker
  script:
  - docker --version
  - docker build -t hr -f DockerFile .

# test:
#   image: node:14-alpine
#   tags:
#     - l0cal, d0cker, tim-pc
#   needs:
#     - build
#   script:
#     - pwd
#     - set DB_NAME=%DB_NAME%
#     - set DB_USER=%DB_USER%
#     - set DB_PASS=%DB_PASS%
#     - set DB_SERVER=%DB_SERVER%
#     - set JWT=%JWT%
#     - npx mocha test/routes/*.js
