stages:
  - test
  - build

variables:
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASS: $DB_PASS
  DB_SERVER: $DB_SERVER
  JWT: $JWT

# run_unit_test:
#   stage: test
#   image: node:latest
#   tags:
#     - she11
#   before_script:
#     - pwd
#     - cd server
#     - npm install
#   script:
#     - pwd
#     - npx mocha test/routes/*.js
    
build_docker_image:
  stage: build
  tags:
    - she11
  # needs:
  #   - run_unit_test
  script:
    - pwd
    - docker build -t hr123 -f DockerFile .

