stages:
  - build
  - test

build:
  image: docker:latest
  tags:
    - l0cal, d0cker, tim-pc
  script:
    - docker build -t my-app .

before_script:
  - cd server
  - npm install

test:
  image: node:14
  tags:
    - shell, myrunner, timpc
  script:
    - set DB_NAME=%DB_NAME%
    - set DB_USER=%DB_USER%
    - set DB_PASS=%DB_PASS%
    - set DB_SERVER=%DB_SERVER%
    - set JWT=%JWT%
    - npx mocha test/routes/*.js
