stages:
  - test

before_script:
  - cd server
  - npm install

test:
  tags:
    - shell, myrunner, timpc
  script:
    - set DB_NAME=%DB_NAME%
    - set DB_USER=%DB_USER%
    - set DB_PASS=%DB_PASS%
    - set DB_SERVER=%DB_SERVER%
    - set JWT=%JWT%
    - npx mocha test/routes/*.js
