stages:
  - build
  - test

build:
  stage: build
  image: docker:20-dind
  tags:
  - chooseMe
  variables: 
    DOCKER_HOST: tcp://docker:2375/
  services:
  - name: docker:dind
    command: ["--tls=false"]
  script:
  - docker build -t hr -f DockerFile .
  - docker run -p 5000:5000 hr      
# test:
#   image: node:14-alpine
#   tags:
#     - l0cal, d0cker, tim-pc
#   needs:
#     - build
#   script:
#     - pwd
#     - set DB_NAME=%DB_NAME%
#     - set DB_USER=%DB_USER%
#     - set DB_PASS=%DB_PASS%
#     - set DB_SERVER=%DB_SERVER%
#     - set JWT=%JWT%
#     - npx mocha test/routes/*.js
