stages:
  - test

before_script:
  - cd server
  - npm install

test:
  tags:
    - shell, myrunner, timpc
  script:
    - export DB_NAME=$DB_NAME
    - export DB_USER=$DB_USER
    - export DB_PASS=$DB_PASS
    - export DB_SERVER=$DB_SERVER
    - export JWT=$JWT
    - npx mocha test/routes/*.js
