# 使用 Node.js 作為基礎映像檔
FROM node:18.15.0-alpine3.16

# 將工作目錄設置為 React 專案的根目錄
WORKDIR /app

# 將 React 專案的所有文件複製到映像檔中
COPY . .

# 安裝依賴包
RUN npm install

# 建構專案
RUN npm run build

# 暴露端口號 3001 => docker run -p 3001:3000 -d react-docker-demo
EXPOSE 3001

# 執行專案
CMD ["npm", "start"]
